### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by an23lm** [DogLeads/landing#21]

**Comment by jjblek** [comment]
Navbar branch updated with new design.

**Comment by jjblek** [comment]
## Navbar branch update 2
- Career and About pages added with respective navbar routes 
- Replaced <a> tag with nextjs <Link> tag, <a> tag was causing a routing issue
- onClick functionality added to demo button
- Updated eslintrc with next/babel to get rid of error in next config

**Comment by jjblek** [comment]
I reused the header-dropdown-menu component as a placeholder for small screen sizes.

I plan on re-designing the dropdown component to fit the new design. 
Is there a specific design in mind for small screen sizes?
